Remove deprecated coverage pkg (#115)
Recently I found that a previous change not related to workflows is failing  in my other PR
https://github.com/gofrs/uuid/pull/111

It is happening because the package [golang.org/x/tools/cmd/cover](https://pkg.go.dev/golang.org/x/tools/cmd/cover) is no longer active and marked as deprecated, that's why the test is falling 


```
Run go get golang.org/x/tools/cmd/cover
  go get golang.org/x/tools/cmd/cover
  shell: /usr/bin/bash -e {0}
  env:
    GO111MODULE: auto
    GOROOT: /opt/hostedtoolcache/go/1.19.4/x64
cannot find package "golang.org/x/tools/cmd/cover" in any of:
	/opt/hostedtoolcache/go/1.19.4/x64/src/golang.org/x/tools/cmd/cover (from $GOROOT)
	/home/runner/go/src/golang.org/x/tools/cmd/cover (from $GOPATH)
Error: Process completed with exit code 1.
```
The tests are focused on 1.18 e 1.19 we will be fine